# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookstore.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62ookstore.proto\x12\x08tutorial\"S\n\x16\x41\x64\x64\x42ookOptionalRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x11\n\x04year\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x07\n\x05_year\"G\n\x18\x41\x64\x64\x42ookNoOptionalRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\"#\n\x0f\x41\x64\x64\x42ookResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\x32\xb6\x01\n\x10\x42ookstoreService\x12N\n\x0f\x41\x64\x64\x42ookOptional\x12 .tutorial.AddBookOptionalRequest\x1a\x19.tutorial.AddBookResponse\x12R\n\x11\x41\x64\x64\x42ookNoOptional\x12\".tutorial.AddBookNoOptionalRequest\x1a\x19.tutorial.AddBookResponseB\"\n\x08sr.protoB\x16\x42ookstoreServiceProtosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bookstore_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\010sr.protoB\026BookstoreServiceProtos'
  _ADDBOOKOPTIONALREQUEST._serialized_start=29
  _ADDBOOKOPTIONALREQUEST._serialized_end=112
  _ADDBOOKNOOPTIONALREQUEST._serialized_start=114
  _ADDBOOKNOOPTIONALREQUEST._serialized_end=185
  _ADDBOOKRESPONSE._serialized_start=187
  _ADDBOOKRESPONSE._serialized_end=222
  _BOOKSTORESERVICE._serialized_start=225
  _BOOKSTORESERVICE._serialized_end=407
# @@protoc_insertion_point(module_scope)
