# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bookstore_pb2 as bookstore__pb2


class BookstoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddBookOptional = channel.unary_unary(
                '/tutorial.BookstoreService/AddBookOptional',
                request_serializer=bookstore__pb2.AddBookOptionalRequest.SerializeToString,
                response_deserializer=bookstore__pb2.AddBookResponse.FromString,
                )
        self.AddBookNoOptional = channel.unary_unary(
                '/tutorial.BookstoreService/AddBookNoOptional',
                request_serializer=bookstore__pb2.AddBookNoOptionalRequest.SerializeToString,
                response_deserializer=bookstore__pb2.AddBookResponse.FromString,
                )


class BookstoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddBookOptional(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBookNoOptional(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookstoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddBookOptional': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBookOptional,
                    request_deserializer=bookstore__pb2.AddBookOptionalRequest.FromString,
                    response_serializer=bookstore__pb2.AddBookResponse.SerializeToString,
            ),
            'AddBookNoOptional': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBookNoOptional,
                    request_deserializer=bookstore__pb2.AddBookNoOptionalRequest.FromString,
                    response_serializer=bookstore__pb2.AddBookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tutorial.BookstoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookstoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddBookOptional(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tutorial.BookstoreService/AddBookOptional',
            bookstore__pb2.AddBookOptionalRequest.SerializeToString,
            bookstore__pb2.AddBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBookNoOptional(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tutorial.BookstoreService/AddBookNoOptional',
            bookstore__pb2.AddBookNoOptionalRequest.SerializeToString,
            bookstore__pb2.AddBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
